"""
AI Model Generation Service using Gemini Imagen 3
Generates realistic human models based on user specifications
"""

import base64
import io
from datetime import datetime
from pathlib import Path
from PIL import Image
import google.genai as genai

from app.config import VERTEX_PROJECT_ID, VERTEX_LOCATION, RESULTS_DIR


async def generate_ai_model(
    gender: str,
    age_range: str,
    ethnicity: str,
    skin_tone: str,
    body_type: str,
    hair_style: str,
    hair_color: str,
    clothing_style: str,
    pose: str,
    unique_id: str
) -> str:
    """
    Generate a realistic AI model image using Gemini Imagen 3
    
    Args:
        gender: Male, Female, Non-binary
        age_range: 18-25, 26-35, 36-45, 46-60
        ethnicity: Caucasian, African, Asian, Hispanic, Middle Eastern, Mixed
        skin_tone: Fair, Light, Medium, Tan, Brown, Dark
        body_type: Slim, Athletic, Average, Curvy, Plus-size
        hair_style: Short, Medium, Long, Curly, Straight, Wavy, Bald
        hair_color: Black, Brown, Blonde, Red, Gray, White, Dyed
        clothing_style: Casual, Business, Sporty, Elegant, Streetwear
        pose: Standing front, Standing side, Walking, Sitting
        unique_id: Unique identifier for file naming
    
    Returns:
        URL path to the generated model image
    """
    
    print(f"🎨 Generating AI model with Gemini Imagen 3...")
    
    try:
        # Build detailed prompt from user specifications
        MODEL_GENERATION_PROMPT = f"""Generate a highly realistic, professional e-commerce model photograph with the following exact specifications:

PERSON CHARACTERISTICS:
- Gender: {gender}
- Age range: {age_range} years old
- Ethnicity: {ethnicity}
- Skin tone: {skin_tone}
- Body type: {body_type}
- Hair style: {hair_style}
- Hair color: {hair_color}

CLOTHING & POSE:
- Clothing style: {clothing_style} outfit (simple, clean, modern)
- Pose: {pose}
- Expression: Natural, friendly, professional smile

PHOTOGRAPHY REQUIREMENTS:
- Background: Plain white or light gray studio background
- Lighting: Professional studio lighting, soft and even
- Framing: Full body shot if standing, three-quarter body if sitting
- Quality: Ultra-high resolution, sharp focus, professional photography
- Style: E-commerce product photography style
- Camera angle: Eye level, straight-on view

TECHNICAL SPECIFICATIONS:
- Image should be suitable for virtual try-on (clear body outline, visible hands/arms)
- No accessories on hands (watches, bracelets, rings)
- Arms positioned naturally at sides or slightly extended
- Clear separation between body and background
- No shadows on background
- Professional model appearance suitable for fashion e-commerce

OUTPUT: A photorealistic, studio-quality model photograph ready for e-commerce virtual try-on applications."""

        # Configure Gemini client with Vertex AI
        print(f"   🔑 Authenticating with Google...")
        if not VERTEX_PROJECT_ID:
            raise Exception("Service account not configured. Please check .env file.")
        
        print(f"   📌 Using Service Account with Vertex AI")
        print(f"   📌 Project: {VERTEX_PROJECT_ID}")
        print(f"   📌 Location: {VERTEX_LOCATION}")
        
        client = genai.Client(
            vertexai=True,
            project=VERTEX_PROJECT_ID,
            location=VERTEX_LOCATION
        )
        
        print(f"   ✅ Client initialized successfully")
        print(f"   🤖 Calling Gemini API for model generation...")
        print(f"   📝 Model: gemini-2.5-flash-image")
        print(f"   ⏳ Generating AI model (this may take 15-30 seconds)...")
        
        # Call Gemini to generate the model image
        response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=[MODEL_GENERATION_PROMPT],
            config={
                "response_modalities": ["IMAGE"],
                "temperature": 0.7,  # Higher temperature for variety in model generation
            }
        )
        
        print(f"   ✅ Received response from Gemini")
        print(f"   📦 Response type: {type(response)}")
        print(f"   📊 Candidates: {len(response.candidates) if response.candidates else 0}")
        
        # Extract the generated image from response
        if not response.candidates:
            print(f"   ❌ No candidates in response")
            raise Exception("No model image generated by Gemini")
        
        print(f"   🔍 Extracting image from response...")
        generated_image_data = None
        for i, part in enumerate(response.candidates[0].content.parts):
            print(f"   📄 Part {i}: {type(part)}, has inline_data: {hasattr(part, 'inline_data')}")
            if hasattr(part, 'inline_data') and part.inline_data:
                generated_image_data = part.inline_data.data
                print(f"   ✅ Found image data in part {i}")
                break
        
        if not generated_image_data:
            print(f"   ❌ No inline_data found in response parts")
            raise Exception("No image data found in Gemini response")
        
        # Save generated model image
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        model_filename = f"ai_model_{timestamp}_{unique_id}.jpg"
        model_path = RESULTS_DIR / model_filename
        
        # Handle image data - might be bytes or base64 string
        print(f"   💾 Saving generated model image...")
        print(f"   📏 Data type: {type(generated_image_data)}")
        
        if isinstance(generated_image_data, bytes):
            image_bytes = generated_image_data
            print(f"   ✅ Data is already bytes: {len(image_bytes)} bytes")
        elif isinstance(generated_image_data, str):
            image_bytes = base64.b64decode(generated_image_data)
            print(f"   ✅ Decoded from base64: {len(image_bytes)} bytes")
        else:
            raise Exception(f"Unexpected data type: {type(generated_image_data)}")
        
        # Open and save the image
        generated_image = Image.open(io.BytesIO(image_bytes))
        generated_image.save(model_path, "JPEG", quality=95)
        
        print(f"   ✅ AI model generated: {model_filename}")
        print(f"   💾 Saved to: {model_path}")
        
        return f"/static/results/{model_filename}"
        
    except Exception as e:
        print(f"   ❌ Error during model generation: {str(e)}")
        print(f"   📋 Error type: {type(e).__name__}")
        import traceback
        print(f"   📋 Full traceback:")
        traceback.print_exc()
        raise Exception(f"Model generation failed: {str(e)}")
